name:                mooncake
version:             0.1.0.0
github:              "yurtsiv/mooncake"
license:             BSD3
author:              "Stepan Yurtsiv"
maintainer:          "stepan.yurtsiv@gmail.com"
copyright:           "2020 Stepan Yurtsiv"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/yurtsiv/mooncake/blob/master/README.md

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  mooncake-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mooncake

tests:
  mooncake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mooncake
